name: Build and push gRPC files

on:
  push:
    branches:
      - main

jobs:
  generate:
    name: proto lint and generating stubs from protos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Clean up
        run: rm -rf pkg/go

      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
      - name: Generating protos
        run: buf generate

      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: mkdir -p pkg/ts
      - run: pnpm run generate

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Autogenerate stubs from protos