name: Build and push gRPC files

on:
  push:
    branches:
      - main

jobs:
  proto_checks:
    name: proto lint, breaking changes detection and generating stubs from protos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
      - name: Generating protos
        run: buf generate
      - uses: stefanzweifel/git-auto-commit-action@v5